install.packages("covid19.analytics")
library(covid19.analytics)
ag <-covid19.data(case = 'aggregated')
View(ag)
tsc<-covid19.data(case = 'ts-confirmed')
report.summary(Nentries = 10,graphical.output = F)
report.summary(Nentries = 10,graphical.output = T)
tots.per.location(tsc,geo.loc='US')
tots.per.location(tsc,geo.loc='TR')
tots.per.location(tsc,geo.loc='TURKEY')
live.map(tsc)
growth.rate(tsc, geo.loc = 'TURKEY')
generate.SIR.model(tsc, 'TURKEY')
